version: '3.8'

services:
  # api:
  #   build: ./core
  #   container_name: api-dev
  #   volumes:
  #     - ./core:/app
  #   ports:
  #     - 4000:4000
  ui:
    build: ./ui
    container_name: ui-dev
    volumes:
      - ./src:/public
    ports:
      - 3000:3000
