version: '3.8'

services:
  api:
    build:
      context: ./core
    container_name: crm-api
    volumes:
      - ./core:/usr/app
    ports:
      - 5000:5000
  ui:
    build: ./ui
    command: npm start
    container_name: crm-app
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./ui:/app
      - '/app/node_modules'
    ports:
      - 3000:3000
